version: '3.1'

services:

  db:
    image: postgres
    env_file: .env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./tables/init/:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080

  app:
    build: .
    environment:
      POSTGRES_URL: db
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
    database_data:
